# Generated by Django 5.2.13 on 2026-04-25 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='about_headings',
            new_name='about_heading',
        ),
    ]
